apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-configmap
#  namespace: observability
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
    
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    
    compactor:
      compaction:
        block_retention: 1h
    
    querier: {}
    
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo
        wal:
          path: /tmp/tempo/wal
