apiVersion: v1
kind: Service
metadata:
  name: tempo
#  namespace: observability
spec:
  selector:
    app: tempo
  ports:
    - name: grpc
      port: 14250
      targetPort: 14250
    - name: otlp
      port: 4317
      targetPort: 4317
    - name: http
      port: 3200
      targetPort: 3200