spring:
  application:
    name: transactions
  datasource:
    url: jdbc:postgresql://localhost:5434/transactions-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6383
  cache:
    type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8084
stripe:
  webhook:
    secret: <webhook_secret>
  secret:
    key: <secret_key>
  checkout:
    success-url: http://localhost:8084/stripe/success
    cancel-url: http://localhost:8084/stripe/cancel