spring:
  application:
    name: transactions
  datasource:
    url: jdbc:postgresql://localhost:5434/transactions-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6383
  cache:
    type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    metrics:
      tags:
        application: app
      distribution:
        percentiles-histogram:
          http:
            server:
              requests: "true"
    logging:
      pattern:
        level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
      level:
        com.example.app: DEBUG

stripe:
  webhook:
    secret: <webhook_secret>
  secret:
    key: <secret_key>
  checkout:
    success-url: http://localhost:8084/stripe/success
    cancel-url: http://localhost:8084/stripe/cancel