# This file is used to run the Transactions service locally for development and testing purposes.
# It builds the Transactions service image instead of pulling it from the Docker Hub registry.

services:
  transactions-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactions-service
    depends_on:
      - transactions-db
      - transactions-cache
    ports:
      - "8084:8084"
    environment:
      - spring.datasource.url=jdbc:postgresql://transactions-db:5432/transactions-db
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - spring.data.redis.host=transactions-cache
      - spring.data.redis.port=6379
    restart: always

  transactions-db:
    image: postgres
    container_name: transactions-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions-db
    ports:
      - "5434:5432"

  transactions-cache:
    image: redis:latest
    container_name: transactions-cache
    ports:
      - "6383:6379"