# This file is used to run the Notifications service locally for development and testing purposes.
# It builds the Notifications service image instead of pulling it from the Docker Hub registry.

services:
  notifications-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications-service
    depends_on:
      - notifications-db
      - notifications-cache
    ports:
      - "8082:8082"
    environment:
      - spring.data.mongodb.uri=mongodb://root:example@notifications-db:27017/notifications-db?authSource=admin
      - spring.data.mongodb.database=notifications-db
      - spring.data.redis.host=notifications-cache
      - spring.data.redis.port=6379
    restart: always

  notifications-db:
    image: mongo
    container_name: notifications-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: notifications-db

  notifications-cache:
    image: redis:latest
    container_name: notifications-cache
    ports:
      - "6381:6379"