spring:
  application:
    name: search
  data:
    redis:
      host: localhost
      port: 6382
  cache:
    type: redis
server:
  port: 8083
merchants:
  service:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: "true"
  logging:
    pattern:
      level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
    level:
      com.example.app: DEBUG
