# This file is used to run the API Gateway locally for development and testing purposes.
# It builds the API Gateway image instead of pulling it from the Docker Hub registry.

services:
  apigateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "8080:8080"
    restart: always