spring:
  application:
    name: merchants
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/merchants-db?authSource=admin
      database: merchants-db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8081
