apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchants-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merchants
  template:
    metadata:
      labels:
        app: merchants
    spec:
      containers:
        - name: merchants-service
          image: mahmoudaboueleneen/amazon-replica:merchants-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
