apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
    compose_service: users-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        compose_service: users-service
    spec:
      containers:
        - name: users-service
          image: mahmoudaboueleneen/amazon-replica:users-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://users-db-statefulset-0.users-db-service:5432/users-db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: POSTGRES_PASSWORD
            - name: OTEL_SERVICE_NAME
              value: users-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: compose_service=users-service
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: users-service