apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNA==  # base64 for "1234"
  POSTGRES_DB: dXNlcnMtZGI=   # base64 for "users-db"