# This file is used to run the Search service locally for development and testing purposes.
# It builds the Search service image instead of pulling it from the Docker Hub registry.

services:
  search-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-service
    ports:
      - "8083:8083"
    restart: always