apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications-service
          image: mahmoudaboueleneen/amazon-replica:notifications-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
