apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notifications-db-statefulset
spec:
  serviceName: "notifications-db-service"  # Must match headless service
  replicas: 1  # Can scale to more for replica set
  selector:
    matchLabels:
      app: notifications-db
  template:
    metadata:
      labels:
        app: notifications-db
    spec:
      containers:
        - name: notifications-db
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notifications-db-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notifications-db-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: notifications-db-secret
                  key: MONGO_INITDB_DATABASE
          volumeMounts:
            - name: notifications-db-persistent-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: notifications-db-persistent-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi