apiVersion: v1
kind: Secret
metadata:
  name: notifications-db-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==     # "root"
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # "example"
  MONGO_INITDB_DATABASE: bm90aWZpY2F0aW9ucy1kYg== # "notifications-db"
  URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBub3RpZmljYXRpb25zLWRiLXN0YXRlZnVsc2V0LTAubm90aWZpY2F0aW9ucy1kYi1zZXJ2aWNlOjI3MDE3L25vdGlmaWNhdGlvbnMtZGI/YXV0aFNvdXJjZT1hZG1pbg==
  # "mongodb://root:example@notifications-db-statefulset-0.notifications-db-service:27017/notifications-db?authSource=admin"