apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
#  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'spring-apps'
        static_configs:
          - targets: ['your-app-service-name:8080']
