# This file is used to run the Merchants service locally for development and testing purposes.
# It builds the Merchants service image instead of pulling it from the Docker Hub registry.

services:
  merchants-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merchants-service
    depends_on:
      - merchants-db
      - merchants-cache
    ports:
      - "8081:8081"
    environment:
      - spring.data.mongodb.uri=mongodb://root:example@merchants-db:27017/merchants-db?authSource=admin
      - spring.data.mongodb.database=merchants-db
      - spring.data.redis.host=merchants-cache
      - spring.data.redis.port=6379
    restart: always

  merchants-db:
    image: mongo
    container_name: merchants-db
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: merchants-db

  merchants-mongo-express:
    image: mongo-express
    container_name: merchants-mongo-express
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@merchants-db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - merchants-db
    restart: always

  merchants-cache:
    image: redis:latest
    container_name: merchants-cache
    ports:
      - "6380:6379"
