apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search-service
          image: mahmoudaboueleneen/amazon-replica:search-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATA_REDIS_HOST
              value: search-cache-service
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: MERCHANTS_SERVICE_URL
              value: http://merchants-service:8080
            - name: OTEL_SERVICE_NAME
              value: search-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: compose_service=search-service
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: search-service