apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  # 'fake' in base64, this will be replaced dynamically by our deploy.sh script working with our K8s stripe-listener-job
  # if not deploying with deploy.sh, you must manually put the real whsec here after base64 encoding it
  STRIPE_WEBHOOK_SECRET: ZmFrZQ==
  STRIPE_SECRET_KEY: c2tfdGVzdF81MU9BQWdySW5XdkJtZWIxRzduZUF3M3dxSWhRc2dNUVNZYkdtM0xPTmZ2anI0VmJjSmd6UGcxeWVVT0MyY1M3VmdoZng4cDNONlM3MjdGTERXZEtkTUpaeTAwY3ZBT1Zwa20=