apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  # 'fake' in base64, this will be replaced dynamically by our deploy.sh script working with our K8s stripe-listener-job
  # if not deploying with deploy.sh, you must manually put the real whsec here after base64 encoding it
  STRIPE_WEBHOOK_SECRET: ZmFrZQ==
  STRIPE_SECRET_KEY: ZmFrZQ=== # 'fake' in base64, replace with your real Stripe secret key after base64 encoding it