apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_WEBHOOK_SECRET: ZmFrZQ== # 'fake' in base64 # TODO: replace with real secret
  STRIPE_SECRET_KEY: ZmFrZQ== # 'fake' in base64 # TODO: replace with real secret