apiVersion: v1
kind: Secret
metadata:
  name: transactions-db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNA==  # base64 for "1234"
  POSTGRES_DB: dHJhbnNhY3Rpb25zLWRi   # base64 for "transactions-db"