apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-deployment
  labels:
    app: transactions
    compose_service: transactions-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
        compose_service: notifications-service
    spec:
      containers:
        - name: transactions-service
          image: mahmoudaboueleneen/amazon-replica:transactions-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://transactions-db-statefulset-0.transactions-db-service:5432/transactions-db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: transactions-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transactions-db-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: SPRING_DATA_REDIS_HOST
              value: transactions-cache
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_WEBHOOK_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_CHECKOUT_SUCCESS_URL
              value: http://transactions-service:8080/stripe/success
            - name: STRIPE_CHECKOUT_CANCEL_URL
              value: http://transactions-service:8080/stripe/cancel
            - name: OTEL_SERVICE_NAME
              value: transactions-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: compose_service=transactions-service
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: transactions-service
            - name: MERCHANTS_SERVICE_URL
              value: http://merchants-service:8080/products