name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -DskipTests -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin ${{ github.event.before }}
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          cat changed_files.txt
          FILES=$(paste -sd ',' changed_files.txt)
          echo "files=$FILES" >> "$GITHUB_OUTPUT"

      # Can add more checks here for common changes affecting all services, not just the 'shared' directory
      - name: Check if 'shared' directory is changed
        id: shared-changed
        run: |
          if grep -q "shared" changed_files.txt; then
            echo "shared directory has changed. Rebuilding and redeploying all services."
            echo "shared-changed=true" >> $GITHUB_ENV
          else
            echo "shared directory has not changed."
            echo "shared-changed=false" >> $GITHUB_ENV
          fi

      # Build and push images only for changed services
      # TODO: Uncomment these when the services are fully ready.. commented out to save GitHub Actions minutes
#      - name: Build and push API Gateway Image
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'apigateway') }}
#        run: |
#          docker build ./apigateway --tag mahmoudaboueleneen/amazon-replica:apigateway
#          docker push mahmoudaboueleneen/amazon-replica:apigateway
#
#      - name: Build and push Merchants Image
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/merchants') }}
#        run: |
#          docker build ./services/merchants --tag mahmoudaboueleneen/amazon-replica:merchants-service
#          docker push mahmoudaboueleneen/amazon-replica:merchants-service
#
#      - name: Build and push Notifications Image
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/notifications') }}
#        run: |
#          docker build ./services/notifications --tag mahmoudaboueleneen/amazon-replica:notifications-service
#          docker push mahmoudaboueleneen/amazon-replica:notifications-service
#
#      - name: Build and push Search Image
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/search') }}
#        run: |
#          docker build ./services/search --tag mahmoudaboueleneen/amazon-replica:search-service
#          docker push mahmoudaboueleneen/amazon-replica:search-service
#
#      - name: Build and push Transactions Image
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/transactions') }}
#        run: |
#          docker build ./services/transactions --tag mahmoudaboueleneen/amazon-replica:transactions-service
#          docker push mahmoudaboueleneen/amazon-replica:transactions-service
#
#      - name: Build and push Users Image
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/users') }}
#        run: |
#          docker build ./services/users --tag mahmoudaboueleneen/amazon-replica:users-service
#          docker push mahmoudaboueleneen/amazon-replica:users-service

# TODO: Uncomment this when deployment is ready
#  deploy_to_k8s:
#    runs-on: ubuntu-latest
#    needs: build_and_push
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up kubectl
#        uses: azure/setup-kubectl@v1  # TODO: Use the actual action based on our CSP like Google Cloud's `setup-gcloud` if using GKE.
#        with:
#          version: 'latest'
#
#      - name: Set up kubeconfig
#        run: |
#          mkdir -p ~/.kube
#          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
#        env:
#          KUBECONFIG: ${{ secrets.KUBECONFIG }}
#
#      - name: Apply RabbitMQ Deployment
#        run: |
#          kubectl apply -f k8s/rabbitmq/rabbitmq-secret.yaml
#          kubectl apply -f k8s/rabbitmq/rabbitmq-deployment.yaml
#          kubectl apply -f k8s/rabbitmq/rabbitmq-service.yaml
#
#      - name: Apply API Gateway Deployment
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'apigateway') }}
#        run: |
#          kubectl apply -f k8s/apigateway/apigateway-ingress.yaml
#          kubectl apply -f k8s/apigateway/apigateway-deployment.yaml
#          kubectl apply -f k8s/apigateway/apigateway-service.yaml
#
#      - name: Apply Merchants Deployment
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/merchants') }}
#        run: |
#          kubectl apply -f k8s/services/merchants/merchants-cache-deployment.yaml
#          kubectl apply -f k8s/services/merchants/merchants-cache-service.yaml
#          kubectl apply -f k8s/services/merchants/merchants-db-secret.yaml
#          kubectl apply -f k8s/services/merchants/merchants-db-service.yaml
#          kubectl apply -f k8s/services/merchants/merchants-db-statefulset.yaml
#          kubectl apply -f k8s/services/merchants/merchants-deployment.yaml
#          kubectl apply -f k8s/services/merchants/merchants-service.yaml
#
#      - name: Apply Notifications Deployment
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/notifications') }}
#        run: |
#          kubectl apply -f k8s/services/notifications/notifications-cache-deployment.yaml
#          kubectl apply -f k8s/services/notifications/notifications-cache-service.yaml
#          kubectl apply -f k8s/services/notifications/notifications-db-secret.yaml
#          kubectl apply -f k8s/services/notifications/notifications-db-service.yaml
#          kubectl apply -f k8s/services/notifications/notifications-db-statefulset.yaml
#          kubectl apply -f k8s/services/notifications/notifications-deployment.yaml
#          kubectl apply -f k8s/services/notifications/notifications-service.yaml
#
#      - name: Apply Search Deployment
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/search') }}
#        run: |
#          kubectl apply -f k8s/services/search/search-cache-deployment.yaml
#          kubectl apply -f k8s/services/search/search-cache-service.yaml
#          kubectl apply -f k8s/services/search/search-deployment.yaml
#          kubectl apply -f k8s/services/search/search-service.yaml
#
#      - name: Apply Transactions Deployment
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/transactions') }}
#        run: |
#          kubectl apply -f k8s/services/transactions/transactions-cache-deployment.yaml
#          kubectl apply -f k8s/services/transactions/transactions-cache-service.yaml
#          kubectl apply -f k8s/services/transactions/transactions-db-secret.yaml
#          kubectl apply -f k8s/services/transactions/transactions-db-service.yaml
#          kubectl apply -f k8s/services/transactions/transactions-db-statefulset.yaml
#          kubectl apply -f k8s/services/transactions/transactions-deployment.yaml
#          kubectl apply -f k8s/services/transactions/transactions-service.yaml
#
#      - name: Apply Users Deployment
#        if: ${{ env.shared-changed == 'true' || contains(steps.changed-files.outputs.files, 'services/users') }}
#        run: |
#          kubectl apply -f k8s/services/users/users-db-secret.yaml
#          kubectl apply -f k8s/services/users/users-db-service.yaml
#          kubectl apply -f k8s/services/users/users-db-statefulset.yaml
#          kubectl apply -f k8s/services/users/users-deployment.yaml
#          kubectl apply -f k8s/services/users/users-service.yaml
#
#      - name: Check Deployment and StatefulSet Status
#        run: |
#          # Get all resources to see a broad overview
#          kubectl get all
#
#          # Check status for all Deployments
#          kubectl rollout status deployment/apigateway-deployment --timeout=900s
#          kubectl rollout status deployment/merchants-deployment --timeout=900s
#          kubectl rollout status deployment/notifications-deployment --timeout=900s
#          kubectl rollout status deployment/search-deployment --timeout=900s
#          kubectl rollout status deployment/transactions-deployment --timeout=900s
#          kubectl rollout status deployment/users-deployment --timeout=900s
#
#          # Check status for all StatefulSets
#          kubectl rollout status statefulset/merchants-db-statefulset --timeout=900s
#          kubectl rollout status statefulset/notifications-db-statefulset --timeout=900s
#          kubectl rollout status statefulset/transactions-db-statefulset --timeout=900s
#          kubectl rollout status statefulset/users-db-statefulset --timeout=900s
#
#          # Wait for pods to be ready (ensure pods for each service are up and running)
#          kubectl wait --for=condition=ready pod -l app=apigateway --timeout=600s
#          kubectl wait --for=condition=ready pod -l app=merchants --timeout=600s
#          kubectl wait --for=condition=ready pod -l app=notifications --timeout=600s
#          kubectl wait --for=condition=ready pod -l app=search --timeout=600s
#          kubectl wait --for=condition=ready pod -l app=transactions --timeout=600s
#          kubectl wait --for=condition=ready pod -l app=users --timeout=600s
#
#          # Check if services are correctly applied (they should be after kubectl apply)
#          kubectl describe svc apigateway-service
#          kubectl describe svc merchants-service
#          kubectl describe svc notifications-service
#          kubectl describe svc search-service
#          kubectl describe svc transactions-service
#          kubectl describe svc users-service

  notify_discord:
    runs-on: ubuntu-latest
    # TODO: Uncomment when deploy_to_k8s job is ready
    # needs: deploy_to_k8s

    steps:
      - name: Set up timestamp
        id: timestamp
        run: |
          TIMESTAMP=$(date -d "${{ github.event.head_commit.timestamp }}" "+%Y-%m-%d %H:%M:%S %Z")
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Notify Discord on success
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          COMMIT_LINK="[View Commit]($COMMIT_URL)"
          WORKFLOW_NAME="${{ github.workflow }}"
          BUILD_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          BUILD_LINK="[View Logs]($BUILD_URL)"
          TIMESTAMP="${{ env.TIMESTAMP }}"

          PAYLOAD=$(jq -n \
            --arg title "Kubernetes Deployment ✅" \
            --arg desc "All services have been successfully deployed to Kubernetes." \
            --argjson color 3066993 \
            --arg branch "$BRANCH_NAME" \
            --arg commit "$COMMIT_MESSAGE" \
            --arg author "$COMMIT_AUTHOR" \
            --arg commit_url "$COMMIT_LINK" \
            --arg workflow "$WORKFLOW_NAME" \
            --arg build_url "$BUILD_LINK" \
            --arg timestamp "$TIMESTAMP" \
            '{
              embeds: [{
                title: $title,
                description: $desc,
                color: $color,
                fields: [
                  { name: "Branch", value: $branch, inline: true },
                  { name: "Commit", value: $commit, inline: true },
                  { name: "Author", value: $author, inline: true },
                  { name: "Commit URL", value: $commit_url, inline: false },
                  { name: "Workflow", value: $workflow, inline: false },
                  { name: "Run", value: $build_url, inline: false },
                  { name: "Timestamp", value: $timestamp, inline: true }
                ]
              }]
            }')

          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$DISCORD_WEBHOOK_URL"

      - name: Notify Discord on failure
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          COMMIT_LINK="[View Commit]($COMMIT_URL)"
          WORKFLOW_NAME="${{ github.workflow }}"
          BUILD_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          BUILD_LINK="[View Logs]($BUILD_URL)"
          TIMESTAMP="${{ env.TIMESTAMP }}"

          PAYLOAD=$(jq -n \
            --arg title "Kubernetes Deployment ❌" \
            --arg desc "Deployment to Kubernetes failed. Please check the logs." \
            --argjson color 15158332 \
            --arg branch "$BRANCH_NAME" \
            --arg commit "$COMMIT_MESSAGE" \
            --arg author "$COMMIT_AUTHOR" \
            --arg commit_url "$COMMIT_LINK" \
            --arg workflow "$WORKFLOW_NAME" \
            --arg build_url "$BUILD_LINK" \
            --arg timestamp "$TIMESTAMP" \
            '{
              embeds: [{
                title: $title,
                description: $desc,
                color: $color,
                fields: [
                  { name: "Branch", value: $branch, inline: true },
                  { name: "Commit", value: $commit, inline: true },
                  { name: "Author", value: $author, inline: true },
                  { name: "Commit URL", value: $commit_url, inline: false },
                  { name: "Workflow", value: $workflow, inline: false },
                  { name: "Run", value: $build_url, inline: false },
                  { name: "Timestamp", value: $timestamp, inline: true }
                ]
              }]
            }')

          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$DISCORD_WEBHOOK_URL"
